version: '3.3'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Example environment variable

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge