version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: DOCKERFILE
    ports:
      - "8443:8443"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Example environment variable

  frontend:
    build:
      context: ./front-end
      dockerfile: DOCKERFILE
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge