[project]
name = "eCommerce"

[plugins]
[plugins.backend]
service = "backend"
dockerfile = "back-end/DOCKERFILE"
build_command = "mvn clean package -DskipTests"
start_command = "java -jar /app/target/*.jar app.jar"
port = 8080

[plugins.frontend]
service = "frontend"
dockerfile = "front-end/DOCKERFILE"
build_command = "npm install && npm run build"
start_command = "nginx -g 'daemon off;'"
port = 80
