server:
  port: 8443
  ssl:
    enabled: true
    key-alias: ecommerce
    key-store: classpath:ecommerce-keystore.p12
    key-store-password: secret
    key-store-type: JKS

logging:
  level:
    org.springframework.security: DEBUG

auth0:
  audience: http://ecommerce/api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-usnrgcejoh3hh0zu.us.auth0.com/
  cors:
    allowedOrigins: https://localhost:4200

  data:
    rest:
      detection-strategy: ANNOTATED
      base-path: /api
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # Uncomment for MySQL Configuration
  # datasource:
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #   username: ecommerceapp
  #   password: ecommerceapp
  # jpa:
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL8Dialect
